import React, { useState } from "react";
import { Scale, HeartHandshake, FileText, Gavel, BookOpen, AlertCircle, CheckCircle, HelpCircle } from "lucide-react";

interface LawCard {
  title: string;
  subtitle: string;
  description: string;
  keyPoints: string[];
  citation: string;
}

interface CivicMisconception {
  question: string;
  answerOnTrue: string;
  myth: string;
}

export default function JusticeShieldSection() {
  const [activeLawIndex, setActiveLawIndex] = useState<number>(0);
  const [quizAnswers, setQuizAnswers] = useState<{ [key: number]: boolean }>({});
  const [revealedQuiz, setRevealedQuiz] = useState<{ [key: number]: boolean }>({});

  const basicLaws: LawCard[] = [
    {
      title: "Pro Bono Publico",
      subtitle: "The Covenant of Equal Representation",
      description: "Pro bono legal work is legal service performed voluntarily and free of charge. Unlike commercial litigation, pro bono acts as the ultimate guarantor of constitutional equity, bridging the financial divide so that low-income citizens can assert critical civil rights in local and municipal hearings.",
      keyPoints: [
        "Derived from 'pro bono publico', meaning 'for the public good'.",
        "Many local bar associations require attorneys to contribute annual voluntary hours.",
        "Crucial for filing zoning objections, public record requests, and protection against unjust code enforcement."
      ],
      citation: "ABA Model Rule 6.1"
    },
    {
      title: "Pro Se Self-Representation",
      subtitle: "The Inherent Right to Self-Advocacy",
      description: "You have a constitutionally protected right to represent yourself in any American court, administrative board, or civil hearing. Known as proceeding 'Pro Se', this means you hold complete command of your legal arguments, filings, and evidentiary submissions without being forced to pay attorney trial retainers.",
      keyPoints: [
        "In Section 35 of the Judiciary Act of 1789, Congress declared that litigants can plead their own cases.",
        "Courts must hold pro se litigants' pleadings to less stringent standards than formal attorney briefs.",
        "Pro Se filings require adherence to municipal deadline rules, emphasizing basic procedural education."
      ],
      citation: "28 U.S. Code § 1654"
    },
    {
      title: "The Due Process Clause",
      subtitle: "Shield Against Arbitrary Municipal Execution",
      description: "No local department, building inspector, or police division can deprive you of life, liberty, or property without proper legal proceedings and fair notice. This means you have an absolute right to an impartial hearing before any fine can be locked into a final judgment.",
      keyPoints: [
        "Requires written, articulate citation notices describing the alleged violation.",
        "Guarantees a clear administrative appeals route before property seizure or entry.",
        "Guarantees the opportunity to cross-examine city inspectors or regulatory witnesses."
      ],
      citation: "U.S. Constitution, 14th Amendment"
    },
    {
      title: "Public Records Access (FOIA)",
      subtitle: "Sovereign Inquest of Institutional Activities",
      description: "Any formal policy, emails between developers and zoning committees, or citation history generated by public employees must be disclosed to citizens upon request. You have the statutory power to audit local registries to spot back-room deals or regulatory compliance issues.",
      keyPoints: [
        "Governed in all 50 states by local Freedom of Information Acts (Sunshine Laws).",
        "Municipalities must respond to record requests within a strictly limited statutory timeline (usually 5-10 days).",
        "Fees charged for search and copying must be minimal and closely tied to actual operational costs."
      ],
      citation: "5 U.S.C. § 552 / State Sunshine Statutes"
    }
  ];

  const legalMyths: CivicMisconception[] = [
    {
      question: "Are public authorities legally permitted to declare an entire public sidewalk 'off-limits' to filming?",
      myth: "MYTH: Officers can instantly forbid video recordation on public walkways using general privacy arguments.",
      answerOnTrue: "No. You have a First Amendment right to film officers performing their statutory duties in public spaces. As long as you do not physically obstruct their operational path or create an active hazard, recording from a public sidewalk is fully protected."
    },
    {
      question: "If an administrative code officer issues a fine, does it instantly become a lien on your residence without a hearing?",
      myth: "MYTH: Building citations bypass municipal boards and attach directly as property judgments.",
      answerOnTrue: "No. Under Due Process, a citation is merely an allegation. It cannot become a final lien until you are issued a formal hearing notice, given the right to plead your defense, and a neutral magistrate issues an official final order."
    },
    {
      question: "Can an attorney do Pro Bono work but then charge you surprise trial fees or research markups?",
      myth: "MYTH: Pro Bono representation permits retroactive back-billing for hourly trial preparation.",
      answerOnTrue: "No. True Pro Bono representation is agreed upon in a signed retainer contract defining a waiver of fee rates. While external court filing fees are sometimes paid by the client, the core attorney services remain entirely complimentary as defined by ABA ethics rules."
    }
  ];

  return (
    <section id="justice-shield" className="py-24 bg-[#001a4d] border-t border-[#d4af37]/25 relative overflow-hidden">
      {/* Background visual accents */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-[#d4af37]/5 blur-[120px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Header Block */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-sm bg-[#d4af37]/10 border border-[#d4af37]/20 text-[#d4af37] text-xs font-mono tracking-wider uppercase mb-4">
            <BookOpen className="w-3.5 h-3.5" /> Civic Shield Educational Hub
          </div>
          <h2 className="text-3xl sm:text-5xl font-serif font-normal italic tracking-tight text-white mb-2">
            The Justice <span className="text-[#d4af37] font-serif not-italic">Shield</span>
          </h2>
          <p className="text-[10px] font-mono text-[#d4af37]/75 uppercase tracking-[0.25em]">
            Bridging Civic Advocacy, Eliminating Fear, Securing Procedural Integrity
          </p>
          <p className="mt-5 text-gray-300 text-sm leading-relaxed max-w-xl mx-auto font-light">
            Procedural fear disappears when you speak the language of absolute statutory law. Explore simple, structured legal reviews on self-representation, pro-bono ethics, and due process protocols below.
          </p>
        </div>

        {/* Tab-like basic laws panel */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Law List Sidebar - 4 cols */}
          <div className="lg:col-span-4 space-y-3">
            <h4 className="text-[10px] font-mono text-[#d4af37] uppercase tracking-widest mb-4 block">
              Core Legal Concepts
            </h4>
            {basicLaws.map((law, idx) => (
              <button
                key={idx}
                onClick={() => setActiveLawIndex(idx)}
                className={`w-full text-left p-4 rounded-sm border transition-all text-xs flex items-center justify-between group cursor-pointer ${
                  activeLawIndex === idx
                    ? "bg-[#d4af37]/15 border-[#d4af37] text-white"
                    : "bg-[#001233]/70 border-[#d4af37]/10 hover:border-[#d4af37]/30 text-gray-300"
                }`}
              >
                <div>
                  <p className={`font-serif font-semibold text-sm transition-colors ${
                    activeLawIndex === idx ? "text-[#d4af37]" : "group-hover:text-[#d4af37]"
                  }`}>
                    {law.title}
                  </p>
                  <p className="text-[10px] font-mono text-gray-400 mt-1 uppercase tracking-wider">{law.citation}</p>
                </div>
                <Scale className={`w-4 h-4 transition-transform duration-300 ${
                  activeLawIndex === idx ? "rotate-12 text-[#d4af37]" : "text-gray-500 group-hover:text-gray-300"
                }`} />
              </button>
            ))}
          </div>

          {/* Active Law Description Display - 8 cols */}
          <div className="lg:col-span-8 bg-[#001233]/95 border border-[#d4af37]/20 p-6 sm:p-8 rounded-sm shadow-2xl space-y-6 relative">
            <div className="absolute top-4 right-4 text-[9px] font-mono font-bold text-gray-500 tracking-wider">
              SECTION DETAILED OUTLINE
            </div>

            <div className="flex items-center gap-3">
              <div className="p-3 bg-[#d4af37]/10 border border-[#d4af37]/20 text-[#d4af37] rounded-sm">
                {activeLawIndex === 0 && <HeartHandshake className="w-6 h-6" />}
                {activeLawIndex === 1 && <FileText className="w-6 h-6" />}
                {activeLawIndex === 2 && <Gavel className="w-6 h-6" />}
                {activeLawIndex === 3 && <Scale className="w-6 h-6" />}
              </div>
              <div>
                <h3 className="text-xl font-serif text-white">{basicLaws[activeLawIndex].title}</h3>
                <p className="text-[10px] font-mono text-[#d4af37] uppercase tracking-wider">
                  {basicLaws[activeLawIndex].citation} • {basicLaws[activeLawIndex].subtitle}
                </p>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-gray-300 font-sans font-light leading-relaxed">
              {basicLaws[activeLawIndex].description}
            </p>

            <div className="border-t border-[#d4af37]/15 pt-5 space-y-3">
              <p className="text-[10px] font-mono text-[#d4af37] uppercase tracking-widest font-bold">
                Critical Compliance Checkpoints & Realities:
              </p>
              <ul className="space-y-2.5">
                {basicLaws[activeLawIndex].keyPoints.map((point, pIdx) => (
                  <li key={pIdx} className="flex items-start gap-2.5 text-xs text-gray-300">
                    <CheckCircle className="w-4 h-4 text-[#d4af37] shrink-0 mt-0.5" />
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

        </div>

        {/* Dynamic Legal Mythbuster Panel */}
        <div className="mt-16 bg-[#001233]/70 border border-[#d4af37]/15 p-6 sm:p-8 rounded-sm space-y-6">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-[#d4af37]" />
            <h4 className="text-sm font-mono uppercase tracking-wider text-white font-bold">
              Campaign Citizen Mythbuster
            </h4>
          </div>
          <p className="text-xs text-gray-300 font-sans font-light">
            Test your legal literacy bounds below by reviewing common legal interactions. Click any myth cards below to reveal verified legal explanations.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-2">
            {legalMyths.map((myth, idx) => (
              <div 
                key={idx} 
                className="bg-[#001a4d]/90 border border-[#d4af37]/15 p-5 rounded-sm hover:border-[#d4af37]/40 transition-all flex flex-col justify-between"
              >
                <div className="space-y-3">
                  <span className="text-[9px] font-mono font-bold text-red-400 bg-red-950/20 border border-red-500/10 py-0.5 px-2 rounded-sm inline-block uppercase">
                    Misconception {idx + 1}
                  </span>
                  <p className="text-xs font-serif font-semibold text-white leading-relaxed">
                    {myth.question}
                  </p>
                  <p className="text-[10px] font-mono text-gray-400 italic">
                    {myth.myth}
                  </p>
                </div>

                <div className="pt-4 border-t border-[#d4af37]/10 mt-4">
                  {revealedQuiz[idx] ? (
                    <div className="text-xs text-gray-300 leading-relaxed font-sans space-y-1 bg-[#d4af37]/5 p-2.5 rounded-sm border border-[#d4af37]/15">
                      <p className="font-mono text-[9px] text-[#d4af37] font-bold uppercase">VERIFIED LAW STATUS :</p>
                      <p>{myth.answerOnTrue}</p>
                    </div>
                  ) : (
                    <button
                      onClick={() => setRevealedQuiz(p => ({ ...p, [idx]: true }))}
                      className="w-full text-center py-2 bg-[#d4af37]/10 hover:bg-[#d4af37]/25 text-[#d4af37] text-[10px] uppercase font-mono font-bold rounded-sm border border-[#d4af37]/20 transition-all cursor-pointer"
                    >
                      Expose Legal Reality
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  );
}
